### ISSUE TITLE
Wrong UTC time for airports 

### ISSUE THREAD

**Issue by zyzyzyhaha** [liamcryan/airporttime#2]
AMS time (2020/10/27/23/00) should be (2020/10/27/22/00) in UTC but return (2020/10/27/21/00) from your code.
Same issue for CDG. It seems that the issue happens when local time is ahead of UTC time.

**Comment by liamcryan** [comment]
Let's try an example:

```
from airporttime import AirportTime
import datetime

cdg = AirportTime(iata_code='CDG')
utc_time = cdg.to_utc(datetime.datetime(2020, 10, 27, 23, 0)
print(utc_time)
2020-10-27 22:00:00+00:00
```

So in this example, we have a time of 23:00 on Oct 27 at CDG.  When we convert to UTC we see 22:00.  This agrees with your comment above.  I think you may be interpreting the results backwards - let me know if I misunderstood anything.

Thanks for checking out this library.  Let me know if the README is confusing or have comments on how to make things clearer.

I have found in practice this library is pretty good at conversions in most cases.  Occasionally the conversion will be of by 1 hour due to daylight savings time errors.
